name: Download Datasource and generate embeddings

on: 
  workflow_dispatch:
    inputs:
      jsonData:
        required: true
        type: string

jobs:
  download-and-gen-embeddings:
    runs-on: ubuntu-latest
    steps:  
      - name: "Checking out the repo"
        uses: actions/checkout@v4 

      - name: "Installing bun"
        uses: oven-sh/setup-bun@v2

      - name: "Trigger Script" 
        env:
          jsonData: ${{inputs.jsonData}}
        run: |
          echo "Running the script"
          bun run embedder/index.ts "$jsonData"
