name: Download Datasource and generate embeddings

on: 
  workflow_dispatch:
    inputs:
      jsonData:
        required: true
        type: string

jobs:
  download-and-gen-embeddings:
    runs-on: ubuntu-latest
    steps: 
      - name: "parsing inputs" 
        run: echo "${{inputs.jsonData}}"
