name: Download Datasource and generate embeddings

on: 
  workflow_dispatch:
    inputs:
      jsonData:
        required: true
        type: string

permissions:
  contents: write

jobs:
  download-and-gen-embeddings:
    runs-on: ubuntu-latest
    environment: ragger
    steps:  
      - name: "Checking out the repo"
        uses: actions/checkout@v4 

      - name: "Installing bun"
        uses: oven-sh/setup-bun@v2

      - name: "Setup embedder"
        run: | 
          cd embedder
          bun i 
          bun run setup

      - name: "Pipeline" 
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
          jsonData: ${{inputs.jsonData}}
        run: |
          echo "Running the script"
          bun run embedder/index.ts "$jsonData"

      - name: "update the hash-store"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add hash-store
          git commit -m "[automated] updating hash-store"
          git push origin main
